# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{iso_country_codes}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["alex"]
  s.date = %q{2011-10-27}
  s.description = %q{ISO country code and currency library}
  s.email = %q{alexrabarts@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "Manifest.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "lib/iso_country_codes.rb",
    "lib/iso_country_codes/code.rb",
    "lib/iso_country_codes/iso_3166_1.rb",
    "lib/iso_country_codes/iso_4217.rb",
    "lib/iso_country_codes/iso_country_codes.rb",
    "rakelib/cultivate.rake",
    "rakelib/iso_3166_1.rake",
    "rakelib/iso_3166_1.rb",
    "rakelib/iso_3166_1.rb.erb",
    "test/iso_country_codes_test.rb"
  ]
  s.homepage = %q{http://github.com/alexrabarts/iso_country_codes}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Provides ISO 3166-1 country codes/names and ISO 4217 currencies.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

